blog/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("post/<slug:title>/", views.post, name="post"),
    path("category/<str:name>/", views.category, name="category"),
    path("search/", views.search, name="search"),
    path("create-post/", views.create_post, name="create_post"),
    path('login/', LoginView.as_view(), name='blog_login'),
    # path('logout/', LogoutView.as_view(), name='blog_logout'),
    path('logout/', views.custom_logout, name='blog_logout'),
    path('accounts/profile/', views.user_profile, name='user_profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('my-posts/', views.my_posts, name='my_posts'),
    path('delete-post/<slug:slug>/', views.delete_post, name='delete_post'),
    path('register/', views.register, name='register'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

website/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('shop/', include('shop.urls', namespace='shop')), #, namespace='shop'
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name="Назва")
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_created=True)
    stock = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('name',)
        indexes = [
            models.Index(fields=['id', 'slug'],)
        ]
        verbose_name = "Товар"
        verbose_name_plural = " Товари"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


# def product_list(request, category_slug=None):
#     category = None
#     categories = Category.objects.all()
#     products = Product.objects.filter(available=True)
#     if category_slug:
#         categories = get_object_or_404(Category, slug=category_slug)
#         products = products.filter(category=category)
#     context = {'category': category, 'categories': categories, 'products': products}
#     return render(request, "shop/product/list.html", context)

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {'category': category, 'categories': categories, 'products': products}
    return render(request, "shop/product/list.html", context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, "shop/product/detail.html", {"product": product, "cart_product_form": CartAddProductForm()})

templates/shop/product/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-6">
                <div class="product-detail">
                    <div class="text-center">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %} {% endif %}" class="img-responsive center-block" alt="">
                    </div>
                    <h1 class="text-center">{{ product.name }}</h1>
                    <h2 class="text-center">
                        <a href="{{ product.category.get_absolute_url }}" class="btn btn-link">{{ product.category }}</a>
                    </h2>
                    <p class="text-center price lead">${{ product.price }}</p>
                    <div class="product-description text-center" style="font-size: 1.2em; margin-top: 20px; max-width: 80%; margin-left: auto; margin-right: auto;">
                        <p>{{ product.description|linebreaks }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
<form action="{% url 'cart:cart_add' product.id %}" method="post" class="form-inline">
    {% csrf_token %}

    <div style="padding:5px" class="form-group">
        {{ cart_product_form }}
    </div><br>

    <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Добавить в корзину
    </button>
</form>

{% endblock %}

templates/shop/product/list.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}


<div id="main" class="product-list" style="text-align: center; margin-bottom: 20px;">
    <h1 style="padding: 20px">{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>

    <div class="row">
        {% for product in products %}
            <div class="col-md-6 col-sm-12 mb-4" style="margin-bottom: 1.5rem;">
                <div class="card" style="border-radius: 12px; padding: 20px; transition: box-shadow 0.3s ease-in-out; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"
                             class="card-img-top"
                             alt=""
                             style="border-radius: 12px 12px 0 0; object-fit: cover; height: 300px; width: 100%;">
                    </a>
                    <div class="card-body" style="padding: 15px;">
                        <h5 class="card-title" style="font-size: 1.4rem; font-weight: bold; color: #333;">
                            <a href="{{ product.get_absolute_url }}" style="color: inherit; text-decoration: none;">{{ product.name }}</a>
                        </h5>
                        <b class="card-text" style="font-size: 1rem; color: #555;">
                            {% if product.description %}
                                {{ product.description }}
                            {% else %}
                                Нет описания
                            {% endif %}
                        </b>
                        <p class="card-text" style="font-size: 1.1rem; font-weight: bold; color: #333;">$ {{ product.price }}</p>
                        <a href="{{ product.get_absolute_url }}" class="btn btn-primary" style="background-color: #007bff; border-color: #007bff; padding: 8px 16px; text-transform: uppercase; font-weight: bold; text-decoration: none; border-radius: 5px;">Перейти</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock %}